language: node_js
node_js:
- '10'
addons:
  apt:
    packages:
    - jq
branches:
  only:
  - master
install: true
script: true
before_deploy:
- git config --local user.name "hobbyquaker"
- git config --local user.email "hobbyquaker@gmail.com"
- npm install && npm run build
- git tag v$(jq -r ".version" package.json)
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
